{
 "title": "overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Ben Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blast13_ben_blast_running / blast13_ben_blast_size",
     "legendFormat": "blast13_ben_blast"
    },
    {
     "expr": "blast14_ben_blast_running / blast14_ben_blast_size",
     "legendFormat": "blast14_ben_blast"
    },
    {
     "expr": "blast15_ben_blast_running / blast15_ben_blast_size",
     "legendFormat": "blast15_ben_blast"
    },
    {
     "expr": "blast16_ben_blast_running / blast16_ben_blast_size",
     "legendFormat": "blast16_ben_blast"
    },
    {
     "expr": "blast17_ben_blast_running / blast17_ben_blast_size",
     "legendFormat": "blast17_ben_blast"
    },
    {
     "expr": "blast18_ben_blast_running / blast18_ben_blast_size",
     "legendFormat": "blast18_ben_blast"
    },
    {
     "expr": "blast19_ben_blast_running / blast19_ben_blast_size",
     "legendFormat": "blast19_ben_blast"
    },
    {
     "expr": "blast20_ben_blast_running / blast20_ben_blast_size",
     "legendFormat": "blast20_ben_blast"
    },
    {
     "expr": "blast21_ben_blast_running / blast21_ben_blast_size",
     "legendFormat": "blast21_ben_blast"
    },
    {
     "expr": "blast22_ben_blast_running / blast22_ben_blast_size",
     "legendFormat": "blast22_ben_blast"
    },
    {
     "expr": "newick00_ben_newick_running / newick00_ben_newick_size",
     "legendFormat": "newick00_ben_newick"
    },
    {
     "expr": "newick01_ben_newick_running / newick01_ben_newick_size",
     "legendFormat": "newick01_ben_newick"
    },
    {
     "expr": "newick02_ben_newick_running / newick02_ben_newick_size",
     "legendFormat": "newick02_ben_newick"
    }
   ]
  },
  {
   "title": "Ben Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ben_queued_jobs_total", "legendFormat": "queued" },
    { "expr": "ben_running_jobs_total", "legendFormat": "running" },
    { "expr": "ben_finished_jobs_total", "legendFormat": "finished" }
   ]
  },
  {
   "title": "Ben Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "delta(ben_errors_count{job=\"backup\"}[$__rate_interval])",
     "legendFormat": "Counter"
    }
   ]
  },
  {
   "title": "Assignxl Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:8003/assignxl.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Assign Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"ben_assign_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_assign_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_assign_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "Assign Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:8003/assign.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "QC Logs",
   "type": "logs",
   "description": "Logs for ecopcr step",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{job=\"ben_qc_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_qc_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_qc_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "QC Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "source": "url", "type": "json", "url": "http://127.0.0.1:8003/qc.json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Ecopcr Logs",
   "type": "logs",
   "description": "Logs for ecopcr step",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{job=\"ben_ecopcr_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_ecopcr_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_ecopcr_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "Ecopcr Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:8003/ecopcr.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Blast Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{job=\"ben_blast_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_blast_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_blast_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "Blast Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:8003/blast.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "AncestralClust Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{job=\"ben_ac_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_ac_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_ac_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "AncestralClust Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "source": "url", "type": "json", "url": "http://127.0.0.1:8003/ac.json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Newick Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "{job=\"ben_newick_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_newick_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_newick_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "Newick Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:8003/newick.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Tronko Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{job=\"ben_tronko_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_tronko_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_tronko_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "Tronko Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:8003/tronko.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "tronko", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast00"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast06"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast07"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast08"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast09"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast10"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast11"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast12"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast13"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast14"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast15"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast16"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast17"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast18"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast19"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast20"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast21"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast22"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast23"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast24"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast25"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast26"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast27"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast28"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast29"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast30"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast31"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast32"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast33"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast34"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast35"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast36"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast37"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast38"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast39"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast40"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast41"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast42"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast43"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast44"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast45"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast46"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast47"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast49"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast50"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast51"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast52"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast53"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast54"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast55"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast56"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast57"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast58"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast59"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast61"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick06"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick07"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast00"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast06"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast07"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast08"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast09"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast10"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast11"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast12"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast13"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast14"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast15"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast16"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast17"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast18"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast19"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast20"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast21"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast22"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast23"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast24"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast25"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast26"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast27"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast28"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast29"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast30"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast31"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast32"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast33"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast34"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast35"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast36"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast37"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast38"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast39"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast40"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast41"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast42"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast43"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast44"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast45"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast46"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast47"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast49"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast50"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast51"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast52"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast53"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast54"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast55"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast56"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast57"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast58"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast59"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "blast61"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick06"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "newick07"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast00"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast06"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast07"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast08"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast09"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast10"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast11"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast12"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast13"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast14"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast15"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast16"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast17"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast18"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast19"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast20"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast21"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast22"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast23"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast24"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast25"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast26"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast27"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast28"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast29"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast30"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast31"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast32"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast33"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast34"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast35"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast36"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast37"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast38"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast39"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast40"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast41"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast42"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast43"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast44"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast45"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast46"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast47"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast49"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast50"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast51"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast52"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast53"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast54"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast55"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast56"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast57"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast58"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast59"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast61"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick06"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick07"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast00"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast06"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast07"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast08"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast09"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast10"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast11"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast12"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast13"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast14"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast15"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast16"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast17"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast18"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast19"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast20"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast21"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast22"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast23"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast24"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast25"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast26"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast27"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast28"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast29"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast30"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast31"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast32"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast33"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast34"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast35"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast36"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast37"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast38"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast39"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast40"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast41"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast42"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast43"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast44"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast45"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast46"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast47"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast49"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast50"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast51"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast52"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast53"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast54"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast55"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast56"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast57"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast58"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast59"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "blast61"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick06"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "newick07"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast00"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast01"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast05"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast06"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast07"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast08"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast09"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast10"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast11"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast12"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast13"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast14"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast15"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast16"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast17"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast18"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast19"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast20"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast21"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast22"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast23"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast24"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast25"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast26"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast27"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast28"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast29"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast30"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast31"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast32"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast33"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast34"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast35"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast36"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast37"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast38"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast39"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast40"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast41"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast42"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast43"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast44"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast45"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast46"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast47"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast49"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast50"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast51"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast52"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast53"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast54"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast55"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast56"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast57"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast58"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast59"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast61"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick05"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick06"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick07"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast00"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast01"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast05"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast06"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast07"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast08"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast09"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast10"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast11"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast12"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast13"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast14"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast15"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast16"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast17"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast18"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast19"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast20"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast21"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast22"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast23"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast24"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast25"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast26"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast27"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast28"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast29"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast30"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast31"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast32"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast33"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast34"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast35"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast36"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast37"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast38"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast39"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast40"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast41"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast42"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast43"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast44"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast45"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast46"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast47"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast49"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast50"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast51"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast52"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast53"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast54"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast55"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast56"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast57"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast58"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast59"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "blast61"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick05"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick06"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "newick07"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "Network Operational Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "newick03 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast00 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast01 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast02 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast03 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast04 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast05 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast06 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast07 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast08 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast09 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast10 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast11 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast12 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast13 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast14 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast15 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast16 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast17 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast18 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast19 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast20 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast21 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast22 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast23 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast24 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast25 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast26 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast27 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast28 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast29 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast30 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast31 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast32 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast33 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast34 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast35 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast36 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast37 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast38 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast39 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast40 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast41 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast42 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast43 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast44 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast45 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast46 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast47 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast49 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast50 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast51 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast52 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast53 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast54 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast55 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast56 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast57 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast58 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast59 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "blast61 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "newick04 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "newick05 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "newick06 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "newick07 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "ecopcr00 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "ecopcr01 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "ecopcr02 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "ecopcr03 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "ecopcr04 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "tronko00 - {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick03"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast00"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast01"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast02"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast03"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast04"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast05"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast06"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast07"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast08"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast09"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast10"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast11"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast12"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast13"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast14"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast15"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast16"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast17"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast18"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast19"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast20"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast21"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast22"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast23"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast24"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast25"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast26"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast27"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast28"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast29"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast30"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast31"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast32"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast33"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast34"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast35"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast36"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast37"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast38"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast39"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast40"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast41"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast42"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast43"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast44"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast45"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast46"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast47"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast49"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast50"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast51"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast52"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast53"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast54"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast55"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast56"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast57"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast58"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast59"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast61"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick04"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick05"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick06"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick07"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr00"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr01"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr02"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr03"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr04"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko00"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick03 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast00 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast01 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast02 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast03 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast04 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast05 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast06 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast07 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast08 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast09 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast10 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast11 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast12 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast13 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast14 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast15 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast16 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast17 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast18 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast19 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast20 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast21 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast22 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast23 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast24 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast25 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast26 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast27 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast28 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast29 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast30 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast31 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast32 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast33 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast34 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast35 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast36 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast37 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast38 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast39 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast40 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast41 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast42 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast43 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast44 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast45 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast46 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast47 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast49 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast50 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast51 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast52 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast53 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast54 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast55 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast56 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast57 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast58 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast59 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "blast61 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick04 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick05 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick06 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "newick07 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr00 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr01 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr02 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr03 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "ecopcr04 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko00 - {{device}}"
    }
   ]
  }
 ]
}