server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: ben_ecopcr_logs
      __path__: /etc/ben/output/*-ecopcr-*
  - targets:
      - localhost
    labels:
      job: ben_blast_logs
      __path__: /etc/ben/output/*-blast-*
  - targets:
      - localhost
    labels:
      job: ben_ac_logs
      __path__: /etc/ben/output/*-ac-*
  - targets:
      - localhost
    labels:
      job: ben_newick_logs
      __path__: /etc/ben/output/*-newick-*
  - targets:
      - localhost
    labels:
      job: ben_tronko_logs
      __path__: /etc/ben/output/*-tronko-*
  - targets:
      - localhost
    labels:
      job: ben_qc_logs
      __path__: /etc/ben/output/*-qc-*
  - targets:
      - localhost
    labels:
      job: ben_assign_logs
      __path__: /etc/ben/output/*-assign*
  - targets:
      - localhost
    labels:
        job: ben_qc
        __path__: /etc/ben/queue/qc.ini
  - targets:
      - localhost
    labels:
        job: ben_assign
        __path__: /etc/ben/queue/assign.ini
  - targets:
      - localhost
    labels:
        job: ben_ecopcr
        __path__: /etc/ben/queue/ecopcr.ini
  - targets:
      - localhost
    labels:
        job: ben_blast
        __path__: /etc/ben/queue/blast.ini
  - targets:
      - localhost
    labels:
        job: ben_ac
        __path__: /etc/ben/queue/ac.ini
  - targets:
      - localhost
    labels:
        job: ben_newick
        __path__: /etc/ben/queue/newick.ini
  - targets:
      - localhost
    labels:
        job: ben_tronko
        __path__: /etc/ben/queue/tronko.ini